import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    // Layouts
    'src/domains/layouts/index.ts',
    'src/domains/layouts/components/index.ts',
    'src/domains/layouts/hooks/index.ts',
    'src/domains/layouts/utils/index.ts',
    'src/domains/layouts/types/index.ts',
    'src/domains/layouts/theme/index.ts',
    'src/domains/layouts/components/DashboardLayout.tsx',
    'src/domains/layouts/components/DashboardHeader.tsx',
    'src/domains/layouts/components/DashboardSidebar.tsx',
    'src/domains/layouts/components/BrandLogo.tsx',
    'src/domains/layouts/hooks/dashboard.ts',
    'src/domains/layouts/utils/dashboard.ts',
    'src/domains/layouts/types/sidebar.ts',
    'src/domains/layouts/types/layout.ts',
    'src/domains/layouts/types/theme.ts',
    'src/domains/layouts/types/notification.ts',
    'src/domains/layouts/types/user.ts',
    'src/domains/layouts/theme/default.ts',
    'src/domains/layouts/theme/presets.ts',
    'src/domains/layouts/theme/utils.ts',
    // Settings
    'src/domains/settings/index.ts',
    'src/domains/settings/components/index.ts',
    'src/domains/settings/hooks/index.ts',
    'src/domains/settings/utils/index.ts',
    'src/domains/settings/types/index.ts',
    'src/domains/settings/components/SettingsLayout.tsx',
    'src/domains/settings/components/SettingsSection.tsx',
    'src/domains/settings/hooks/useSettings.ts',
    'src/domains/settings/utils/settings.ts',
    'src/domains/settings/types/settings.ts',
    // Onboarding
    'src/domains/onboarding/index.ts',
    'src/domains/onboarding/components/index.ts',
    'src/domains/onboarding/hooks/index.ts',
    'src/domains/onboarding/utils/index.ts',
    'src/domains/onboarding/types/index.ts',
    'src/domains/onboarding/components/OnboardingWizard.tsx',
    'src/domains/onboarding/components/UserTypeStep.tsx',
    'src/domains/onboarding/components/AppFocusStep.tsx',
    'src/domains/onboarding/components/PlatformsStep.tsx',
    'src/domains/onboarding/components/PlanStep.tsx',
    'src/domains/onboarding/hooks/useOnboarding.ts',
    'src/domains/onboarding/utils/onboarding.ts',
    'src/domains/onboarding/types/onboarding.ts',
  ],
  format: ['esm'],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'react-router-dom',
    'react-i18next',
    '@umituz/web-design-system',
    '@umituz/web-design-system/utils',
    '@umituz/web-design-system/atoms',
    'lucide-react',
    'clsx',
    'tailwind-merge',
    'class-variance-authority',
  ],
  esbuildOptions(options) {
    options.banner = {
      js: '"use client";',
    };
  },
});
